### ISSUE TITLE
Failed to reach some repository

### ISSUE THREAD

**Issue by Jiroh** [uzh-rpg/agile_autonomy#1]
_vcs-import < agile_autonomy/dependencies.yaml_
results some errors that failed to reach repositories.

=== ./rpg_common (git) ===
Could not determine ref type of version: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_flightmare (git) ===
Could not determine ref type of version: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_mpl_ros (git) ===
Could not determine ref type of version: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by antonilo** [comment]
Thanks, we'll fix this asap!
