### ISSUE TITLE
open3d_conversions error when catkin build 

### ISSUE THREAD

**Issue by Howardcl** [uzh-rpg/agile_autonomy#26]
[build] Found '71' packages in 0.0 seconds.                                    
[build] Package table is up to date.                                           
Starting  >>> catkin_boost_python_buildtool                                    
Starting  >>> catkin_simple                                                    
Starting  >>> decomp_util                                                      
Starting  >>> mav_msgs                                                         
Starting  >>> mav_state_machine_msgs                                           
Starting  >>> mav_system_msgs                                                  
Starting  >>> motion_primitive_library                                         
Starting  >>> open3d_conversions                                               
Starting  >>> rotors_comm                                                      
Starting  >>> rotors_description                                               
Starting  >>> rotors_evaluation                                                
Starting  >>> rqt_rotors                                                       
Finished  <<< mav_state_machine_msgs                            [ 0.1 seconds ]
Finished  <<< mav_msgs                                          [ 0.1 seconds ]
Starting  >>> mav_planning_msgs                                                
Starting  >>> rotors_control                                                   
Starting  >>> rotors_hil_interface                                             
Starting  >>> rotors_joy_interface                                             
Finished  <<< rotors_evaluation                                 [ 0.1 seconds ]
Finished  <<< catkin_boost_python_buildtool                     [ 0.0 seconds ]
Finished  <<< mav_system_msgs                                   [ 0.1 seconds ]
Finished  <<< rqt_rotors                                        [ 0.1 seconds ]
Finished  <<< catkin_simple                                     [ 0.1 seconds ]
Starting  >>> assimp_catkin                                                    
Starting  >>> catkin_boost_python_buildtool_test                               
Starting  >>> decomp_ros_msgs                                                  
Starting  >>> eigen_catkin                                                     
Starting  >>> flightrender                                                     
Starting  >>> gflags_catkin                                                    
Starting  >>> minimum_jerk_trajectories                                        
Starting  >>> planning_ros_msgs                                                
Starting  >>> quad_launch_files                                                
Starting  >>> quadrotor_msgs                                                   
Starting  >>> rpg_single_board_io                                              
Starting  >>> rpgq_msgs                                                        
Finished  <<< rotors_comm                                       [ 0.1 seconds ]
Finished  <<< rotors_description                                [ 0.1 seconds ]
Finished  <<< rotors_control                                    [ 0.1 seconds ]
Finished  <<< rotors_hil_interface                              [ 0.1 seconds ]
Starting  >>> rotors_gazebo_plugins                                            
Finished  <<< mav_planning_msgs                                 [ 0.1 seconds ]
Starting  >>> mav_comm                                                         
Finished  <<< rotors_joy_interface                              [ 0.1 seconds ]
Finished  <<< decomp_ros_msgs                                   [ 0.1 seconds ]
Finished  <<< quad_launch_files                                 [ 0.1 seconds ]
Finished  <<< gflags_catkin                                     [ 0.1 seconds ]
Starting  >>> glog_catkin                                                      
_______________________________________________________________________________
Warnings   << open3d_conversions:check /home/pc205/agile_autonomy_ws/catkin_aa/logs/open3d_conversions/build.check.022.log
Searching open3D in /usr/local/bin/cmake/
Found OpenMP TRUE    0.9.0.0 OpenMP::OpenMP_CXX
Found Open3D 0.9.0.0
cd /home/pc205/agile_autonomy_ws/catkin_aa/build/open3d_conversions; catkin build --get-env open3d_conversions | catkin env -si  /usr/bin/make cmake_check_build_system; cd -

...............................................................................
Finished  <<< open3d_conversions                                [ 0.5 seconds ]
Finished  <<< eigen_catkin                                      [ 0.1 seconds ]
Starting  >>> numpy_eigen                                                      
Finished  <<< catkin_boost_python_buildtool_test                [ 0.1 seconds ]
Finished  <<< rpgq_msgs                                         [ 0.1 seconds ]
Starting  >>> rpgq_common                                                      
Finished  <<< planning_ros_msgs                                 [ 0.1 seconds ]
Finished  <<< rpg_single_board_io                               [ 0.1 seconds ]
Finished  <<< assimp_catkin                                     [ 0.1 seconds ]
Finished  <<< minimum_jerk_trajectories                         [ 0.1 seconds ]
Finished  <<< flightrender                                      [ 0.1 seconds ]
Finished  <<< quadrotor_msgs                                    [ 0.1 seconds ]
Starting  >>> agile_autonomy_msgs                                              
Starting  >>> quadrotor_common                                                 
Starting  >>> rqt_quad_gui                                                     
Starting  >>> vbat_thrust_calibration                                          
Finished  <<< motion_primitive_library                          [ 0.2 seconds ]
Starting  >>> planning_ros_utils                                               
Finished  <<< decomp_util                                       [ 0.1 seconds ]
Starting  >>> decomp_ros_utils                                                 
Starting  >>> mpl_external_planner                                             
Finished  <<< mav_comm                                          [ 0.1 seconds ]
Finished  <<< rotors_gazebo_plugins                             [ 0.2 seconds ]
Starting  >>> rotors_gazebo                                                    
Finished  <<< glog_catkin                                       [ 0.1 seconds ]
Starting  >>> eigen_checks                                                     
Finished  <<< numpy_eigen                                       [ 0.1 seconds ]
Finished  <<< rpgq_common                                       [ 0.1 seconds ]
Starting  >>> rpgq_command_bridge                                              
Starting  >>> rpgq_components                                                  
Finished  <<< quadrotor_common                                  [ 0.1 seconds ]
Starting  >>> polynomial_trajectories                                          
Starting  >>> position_controller                                              
Starting  >>> sbus_bridge                                                      
Starting  >>> state_predictor                                                  
Starting  >>> trajectory_visualizer                                            
Finished  <<< vbat_thrust_calibration                           [ 0.1 seconds ]
Finished  <<< agile_autonomy_msgs                               [ 0.1 seconds ]
Finished  <<< rqt_quad_gui                                      [ 0.1 seconds ]
Finished  <<< planning_ros_utils                                [ 0.1 seconds ]
Finished  <<< decomp_ros_utils                                  [ 0.1 seconds ]
Starting  >>> decomp_test_node                                                 
Finished  <<< mpl_external_planner                              [ 0.1 seconds ]
Finished  <<< rotors_gazebo                                     [ 0.1 seconds ]
Starting  >>> rotors_simulator                                                 
Finished  <<< eigen_checks                                      [ 0.1 seconds ]
Starting  >>> minkindr                                                         
Finished  <<< rpgq_components                                   [ 0.1 seconds ]
Finished  <<< rpgq_command_bridge                               [ 0.1 seconds ]
Starting  >>> rpgq_simulator                                                   
Finished  <<< polynomial_trajectories                           [ 0.1 seconds ]
Finished  <<< position_controller                               [ 0.1 seconds ]
Finished  <<< trajectory_visualizer                             [ 0.1 seconds ]
Finished  <<< sbus_bridge                                       [ 0.1 seconds ]
Starting  >>> manual_flight_assistant                                          
Finished  <<< state_predictor                                   [ 0.1 seconds ]
Finished  <<< decomp_test_node                                  [ 0.1 seconds ]
Finished  <<< rotors_simulator                                  [ 0.1 seconds ]
Finished  <<< minkindr                                          [ 0.1 seconds ]
Starting  >>> minkindr_conversions                                             
Starting  >>> minkindr_python                                                  
Starting  >>> rpg_common                                                       
Finished  <<< rpgq_simulator                                    [ 0.1 seconds ]
Starting  >>> example_pcd                                                      
Starting  >>> example_vision                                                   
Starting  >>> example_vison                                                    
Finished  <<< manual_flight_assistant                           [ 0.1 seconds ]
Finished  <<< rpg_common                                        [ 0.1 seconds ]
Starting  >>> rpg_rotors_interface                                             
Starting  >>> trajectory_generation_helper                                     
Finished  <<< minkindr_conversions                              [ 0.1 seconds ]
Finished  <<< minkindr_python                                   [ 0.1 seconds ]
Finished  <<< example_vison                                     [ 0.1 seconds ]
Finished  <<< example_vision                                    [ 0.1 seconds ]
Finished  <<< example_pcd                                       [ 0.1 seconds ]
Finished  <<< trajectory_generation_helper                      [ 0.1 seconds ]
Starting  >>> autopilot                                                        
Finished  <<< rpg_rotors_interface                              [ 0.1 seconds ]
Finished  <<< autopilot                                         [ 0.1 seconds ]
Starting  >>> agile_autonomy_utils                                             
Starting  >>> example_control                                                  
Starting  >>> planner_learning                                                 
Starting  >>> rpg_mpc                                                          
Starting  >>> rpg_quadrotor_integration_test                                   
Finished  <<< rpg_quadrotor_integration_test                    [ 0.1 seconds ]
Finished  <<< rpg_mpc                                           [ 0.1 seconds ]
Finished  <<< example_control                                   [ 0.1 seconds ]
Finished  <<< agile_autonomy_utils                              [ 0.1 seconds ]
Starting  >>> mpl_test_node                                                    
Starting  >>> agile_autonomy                                                   
Starting  >>> traj_sampler                                                     
Finished  <<< planner_learning                                  [ 0.1 seconds ]
Finished  <<< agile_autonomy                                    [ 0.1 seconds ]
Finished  <<< traj_sampler                                      [ 0.1 seconds ]
_______________________________________________________________________________
Errors     << mpl_test_node:cmake /home/pc205/agile_autonomy_ws/catkin_aa/logs/mpl_test_node/build.cmake.013.log
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /home/pc205/agile_autonomy_ws/catkin_aa/devel/share/open3d_conversions/cmake/open3d_conversionsConfig.cmake:173 (message):
  Project 'mpl_test_node' tried to find library 'Open3D'.  The library is
  neither a target nor built/installed properly.  Did you compile project
  'open3d_conversions'? Did you find_package() it before the subdirectory
  containing its code is included?
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)

cd /home/pc205/agile_autonomy_ws/catkin_aa/build/mpl_test_node; catkin build --get-env mpl_test_node | catkin env -si  /usr/bin/cmake /home/pc205/agile_autonomy_ws/catkin_aa/src/rpg_mpl_ros/mpl_test_node --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/pc205/agile_autonomy_ws/catkin_aa/devel -DCMAKE_INSTALL_PREFIX=/home/pc205/agile_autonomy_ws/catkin_aa/install -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fdiagnostics-color -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3; cd -

...............................................................................
Failed     << mpl_test_node:cmake                               [ Exited with code 1 ]
Failed    <<< mpl_test_node                                     [ 0.4 seconds ]
[build] Summary: 70 of 71 packages succeeded.                                  
[build]   Ignored:   None.                                                     
[build]   Warnings:  1 packages succeeded with warnings.                       
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 4.2 seconds total.

**Comment by Howardcl** [comment]
![图片](https://user-images.githubusercontent.com/57213519/145797462-39547926-52a0-45a8-8be8-8c6f0d939290.png)

**Comment by racheraven** [comment]
Seems to be an open3d library error.
You may refer to [my answer ](https://github.com/uzh-rpg/agile_autonomy/issues/12#issuecomment-972612526) or [den250400's answer](https://github.com/uzh-rpg/agile_autonomy/issues/10#issuecomment-981095386) for possible solution.

**Comment by Howardcl** [comment]
@racheraven Thank you for your reply! I have tried this method,but it don't works~

**Comment by lilrookie76** [comment]
> 

Hey guy, have you solved this problem?

**Comment by Howardcl** [comment]
@lilrookie76 yes! you can refer to https://blog.csdn.net/wxm__/article/details/121220816#t16

**Comment by Howardcl** [comment]
done
