### ISSUE TITLE
Cannot load simulation environment

### ISSUE THREAD

**Issue by zhengzaiyi** [uzh-rpg/agile_autonomy#46]
When I was running the command `roslaunch agile_autonomy simulation.launch`, something wrong happened as the following image shows: 
![图片](https://user-images.githubusercontent.com/44119778/162176495-0b256648-664c-4213-8035-62a2ef9dbf4c.png)
It kept printing `Ready ? : 0`, the `standalone` has been extracted to the 'flightrender` folder. Is it necessary to build the `standalone` in advance?

**Comment by psun-autel** [comment]
Waiting on further instruction as well. I don't have any errors in your snapshot anymore, but the other outputs are the same as mine. 
Also, I got further error 

 INFO] [1649622827.802552360, 2.876000000]: Unity is ready!
[ERROR] [1649622828.212042755, 3.080000000]: no kernel image is available for execution on the device 209

[ERROR] [1649622828.321543409, 3.135000000]: no kernel image is available for execution on the device 209

[ERROR] [1649622828.459425264, 3.203000000]: no kernel image is available for execution on the device 209

[ERROR] [1649622828.582797969, 3.265000000]: no kernel image is available for execution on the device 209

[ERROR] [1649622828.721430274, 3.334000000]: no kernel image is available for execution on the device 209

^C[ERROR] [1649622828.859060628, 3.403000000]: no kernel image is available for execution on the device 209

**Comment by psun-autel** [comment]
You need to click start and also click arm bridge to see the effect.

**Comment by zhengzaiyi** [comment]
> 

If you're using GPU with Nvidia Ampere structure, you need to add the gpu-code in the CmakeLists

**Comment by zhengzaiyi** [comment]
> Waiting on further instruction as well. I don't have any errors in your snapshot anymore, but the other outputs are the same as mine. Also, I got further error
> 
> INFO] [1649622827.802552360, 2.876000000]: Unity is ready! [ERROR] [1649622828.212042755, 3.080000000]: no kernel image is available for execution on the device 209
> 
> [ERROR] [1649622828.321543409, 3.135000000]: no kernel image is available for execution on the device 209
> 
> [ERROR] [1649622828.459425264, 3.203000000]: no kernel image is available for execution on the device 209
> 
> [ERROR] [1649622828.582797969, 3.265000000]: no kernel image is available for execution on the device 209
> 
> [ERROR] [1649622828.721430274, 3.334000000]: no kernel image is available for execution on the device 209
> 
> ^C[ERROR] [1649622828.859060628, 3.403000000]: no kernel image is available for execution on the device 209

Maybe you are using Nvidia 30XX? If your Gpu is of Ampere structure, you need to add the corresponding gpu-code to CmakeLists.

**Comment by mw9385** [comment]
Have you solved this issue?

**Comment by Hang-Shi** [comment]
> > Waiting on further instruction as well. I don't have any errors in your snapshot anymore, but the other outputs are the same as mine. Also, I got further error
> > INFO] [1649622827.802552360, 2.876000000]: Unity is ready! [ERROR] [1649622828.212042755, 3.080000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.321543409, 3.135000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.459425264, 3.203000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.582797969, 3.265000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.721430274, 3.334000000]: no kernel image is available for execution on the device 209
> > ^C[ERROR] [1649622828.859060628, 3.403000000]: no kernel image is available for execution on the device 209
> 
> Maybe you are using Nvidia 30XX? If your Gpu is of Ampere structure, you need to add the corresponding gpu-code to CmakeLists.

Buddy, could you tell me in detail how to add the corresponding gpu-code to CmakeLists. 1) I'm not sure how to determine the corresponding gpu-code. 2) There are so many CmakeLists that I don't know which one is suitable. 
Waiting for your reply.    ^_^

**Comment by Hang-Shi** [comment]
> > Waiting on further instruction as well. I don't have any errors in your snapshot anymore, but the other outputs are the same as mine. Also, I got further error
> > INFO] [1649622827.802552360, 2.876000000]: Unity is ready! [ERROR] [1649622828.212042755, 3.080000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.321543409, 3.135000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.459425264, 3.203000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.582797969, 3.265000000]: no kernel image is available for execution on the device 209
> > [ERROR] [1649622828.721430274, 3.334000000]: no kernel image is available for execution on the device 209
> > ^C[ERROR] [1649622828.859060628, 3.403000000]: no kernel image is available for execution on the device 209
> 
> Maybe you are using Nvidia 30XX? If your Gpu is of Ampere structure, you need to add the corresponding gpu-code to CmakeLists.

I solved the problem. 1) find the path   /agile_autonomy_ws/catkin_aa/src/agile_autonomy/data_generation/agile_autonomy/CmakeLists.    2)Open the CmakeLists and add  '-gencode=arch=compute_80,code=sm_80'  and  '-gencode=arch=compute_86,code=sm_86'

**Comment by Hang-Shi** [comment]
> Did you solve this issue?

Now you can solve this issue

**Comment by zhengzaiyi** [comment]
> You need to click start and also click arm bridge to see the effect.

HangShi's right, it's all about the gpu structure(I guess you're using Turing)

**Comment by stary-T-sky** [comment]
Did you solve this issue? My terminal also kept printing "Ready ? : 0".

**Comment by zhengzaiyi** [comment]
> Did you solve this issue? My terminal also kept printing "Ready ? : 0".

Yeah, see [this quote](https://github.com/uzh-rpg/agile_autonomy/issues/46#issuecomment-1159749990)

**Comment by 9woods123** [comment]
> Did you solve this issue? My terminal also kept printing "Ready ? : 0".
Should I download the unity exe, and put it in this path "~/agile_autonomy_ws/catkin_aa/src/rpg_flightmare/flightrender" ? This operation is not noted in tutorial or wiki.

**Comment by 9woods123** [comment]
> > Did you solve this issue? My terminal also kept printing "Ready ? : 0".
> 
> Yeah, see [this quote](https://github.com/uzh-rpg/agile_autonomy/issues/46#issuecomment-1159749990)

Do I need to download an unity exe ,and put it in "~/agile_autonomy_ws/catkin_aa/src/rpg_flightmare/flightrender" ?
This operation is not mentioned in tutorials or wiki, and it confuses me .
