### ISSUE TITLE
can't fly when run test_trajectories.py

### ISSUE THREAD

**Issue by AndyYan2** [uzh-rpg/agile_autonomy#48]
When run "python test_trajectories.py --settings_file=config/test_settings.yaml", it will loop as follows:

![图片](https://user-images.githubusercontent.com/44495799/163575982-02c8a46b-3a83-4aea-9599-7e68356f3f36.png)

In rviz, the RGM is NO Image

![图片](https://user-images.githubusercontent.com/44495799/163574784-2de62b20-2686-4607-96a0-cd992784fd14.png)

Check the rostopic, I find many topics received no message. 

![图片](https://user-images.githubusercontent.com/44495799/163575054-f2732de5-1328-4c22-a94d-df396ee369bf.png)
What's wrong with this? It's the fightmare can't  communicate with ROS ? Thanks a lot !

**Comment by AndyYan2** [comment]
Maybe it's because the GPU driver version mismatches since the image can't show. I have solved the problem by reinstall the operating system.

**Comment by mw9385** [comment]
@AndyYan2 Hi, could you write down your hardware specification (including GPU, GPU driver version, cuda version)?
I am struggling with similar issue. Thanks in advance :)

**Comment by AndyYan2** [comment]
My hardware version is as follows:
ubuntu :18.04
CUDA :11.0
GPU :NVIDIA GeForce RTX 2060
GPU driver : 450.51.05
I installed the driver by CUDA. When installing CUDA, it will install the driver automatically.
gcc :7.5.0
g++ :7.5.0
python :3.9.7
open3d : 0.9.0 
Hope it's useful !
