### ISSUE TITLE
Where to Find All the Simulation Envs?

### ISSUE THREAD

**Issue by zhengzaiyi** [uzh-rpg/agile_autonomy#58]
Hi there. As the paper's page 22 shows, a variety of simulation environments were developed. However, I can only find `forest` env while running the simulation. Are the other envs, like `city street`, belong to different Unity projects, or just coordinates somewhere in the `standsalone` given by the [dataset link](https://zenodo.org/record/5517791#.YV2zkGNfhhE)? Appreciation for your answers and time.
<img width="408" alt="image" src="https://user-images.githubusercontent.com/44119778/177499319-fabb447f-5080-4350-b646-52a5734aeeff.png">

**Comment by zyayoung** [comment]
I have the same issue. Have you been able to figure out where the other environments are?

**Comment by Hofalen** [comment]
me too
