### ISSUE TITLE
Possible error in nets.py freeze

### ISSUE THREAD

**Issue by blu666** [uzh-rpg/agile_autonomy#72]
Hi, while looking through the source code, I noticed a tiny error.

In agile_autonomy/planner_learning/src/PlannerLearning/models/nets.py, from line 52-58:
```
               # Freeze only BN
                model = self.backbone[0]
                for layer in model.layers:
                    if layer.name.endswith('_bn'):
                        layer.trainable = True
                    else:
                        layer.trainable = True
```

It seems that the code is not actually freezing the BN layers.

I'm new to this, so I'm not sure if I'm correct.

**Comment by antonilo** [comment]
Thank you for pointing it out. The idea of freezing just BN did not work, so I ended up training the entire thing. Essentially the second if condition was useless. I took that away now!
