### ISSUE TITLE
Failed to reach repository

### ISSUE THREAD

**Issue by EhrazImam** [uzh-rpg/agile_autonomy#8]
vcs-import < agile_autonomy/dependencies.yaml

EEEEEEEEEEEEEEEEEEEE
=== ./assimp_catkin (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./catkin_boost_python_buildtool (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./catkin_simple (git) ===
Could not determine ref type of version: Warning: Permanently added the RSA host key for IP address '13.234.176.102' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./eigen_catkin (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./eigen_checks (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./gflags_catkin (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./glog_catkin (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./mav_comm (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./minimum_jerk_trajectories (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./minkindr (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./minkindr_ros (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./numpy_eigen (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rotors_simulator (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_common (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_flightmare (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_mpc (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_mpl_ros (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_quadrotor_common (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_quadrotor_control (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./rpg_single_board_io (git) ===
Could not determine ref type of version: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by swxgithub** [comment]
How did you solve this problem？

**Comment by yukaryote** [comment]
I'm actually having the same issue. Could you describe how you fixed this?

**Comment by man-do** [comment]
I am having the same issue @EhrazImam .

**Comment by iamrajee** [comment]
Hi, @EhrazImam Did you solve this issue?

**Comment by iamrajee** [comment]
@yukaryote @man-do I resolved this by adding the ssh key to my GitHub account. See [here](https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey) for details. Apparently, the issue occurred because `vcs-import` command try to clone the dependent pkg mentioned in the yaml(similar to what). However, the URL in YAML is of the format `git@github.com:...` Which mean it will require you to setup your ssh keys in your GitHub account (One alternative is to change the URL to HTTP format).

**Comment by maplecod** [comment]
> 我通过将 ssh 密钥添加到我的 GitHub 帐户来解决此问题。有关详细信息，请参阅[此处](https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey)。显然，出现此问题是因为命令尝试克隆 yaml 中提到的依赖 pkg。但是，YAML 中的 URL 的格式是 这意味着它将要求您在 GitHub 帐户中设置 ssh 密钥（一种替代方法是将 URL 更改为 HTTP 格式）。`vcs-import``git@github.com:...`

hi, i want to know how to get the project ssh, or can you tell me the SSH you are using？
