### ISSUE TITLE
Can't  load the unity enviroment

### ISSUE THREAD

**Issue by 9woods123** [uzh-rpg/agile_autonomy#92]
Hello, wonderful work! I have met some problem when I  follow the tutorial.

I follow the tutorials, and build package successfully in Ubuntu 18.04.  
However, when I run：

`roslaunch agile_autonomy simulation.launch`

The terminal keep print: 
```
Ready ? : 0
Ready ? : 0
Ready ? : 0
Ready ? : 0
```
I found that in "~/agile_autonomy_ws/catkin_aa/src/rpg_flightmare/flightrender" , there is no unity binary, while I found that in [https://github.com/uzh-rpg/flightmare](), a untiy binary should be download and put it under the package "flightrender".  The operation is not mentioned in tutorials or wiki of agile_autonomy .

Please help me! Thanks

**Comment by mashenglong** [comment]
Hello,I have the same problem.Can you tell me how to fix it?
